import Foundation
import Network

// MARK: - PAC generation

enum PACGenerator {
    private static let helpers = #"""
    function __ip2n(ip) {
      var p = ip.split(".");
      return ((+p[0]) * 16777216) + ((+p[1]) * 65536) + ((+p[2]) * 256) + (+p[3]);
    }
    function __in(n, r) {
      if (n < 0) return false;
      for (var i = 0; i < r.length; i++) { if (n >= r[i][0] && n <= r[i][1]) return true; }
      return false;
    }
    """#

    static func generate(profiles: [Profile], title: String) -> String {
        var l: [String] = []
        l.append("// Generated by ProxyRouter \(AppInfo.version) — \(safe(title))")
        l.append("// Rules are evaluated top to bottom; the first match wins.")
        l.append(helpers)
        l.append("function FindProxyForURL(url, host) {")
        l.append("  host = host.toLowerCase();")
        l.append("  var __n = -1;")
        l.append("  function N() {")
        l.append("    if (__n !== -1) return __n;")
        l.append(#"    var ip = /^\d{1,3}(\.\d{1,3}){3}$/.test(host) ? host : (host.indexOf(":") >= 0 ? null : dnsResolve(host));"#)
        l.append("    __n = ip ? __ip2n(ip) : -2;")
        l.append("    return __n;")
        l.append("  }")
        for p in profiles {
            l.append("")
            l.append("  // Profile: \(safe(p.name))")
            // excluded destinations skip this profile and fall through to the next one
            let excl = condition(specs: p.parsedExcludes.compactMap(\.spec))
            let pad = excl == nil ? "  " : "    "
            if let excl { l.append("  if (!(\(excl))) {") }
            for r in p.rules where r.enabled {
                if r.action == .proxy && !r.isProxyHostValid { continue }
                guard let cond = condition(for: r) else { continue }
                l.append("\(pad)// \(safe(r.name.isEmpty ? "rule" : r.name)) → \(safe(r.actionSummary))")
                l.append("\(pad)if (\(cond)) return \"\(r.pacResult)\";")
            }
            if excl != nil { l.append("  }") }
        }
        l.append("")
        l.append("  return \"DIRECT\";")
        l.append("}")
        return l.joined(separator: "\n") + "\n"
    }

    static func condition(for rule: Rule) -> String? {
        condition(specs: rule.parsedTargets.compactMap(\.spec))
    }

    static func condition(specs: [TargetSpec]) -> String? {
        guard !specs.isEmpty else { return nil }
        var parts: [String] = []
        var ranges: [(UInt32, UInt32)] = []
        for s in specs {
            switch s {
            case .any: return "true"
            case .host(let h): parts.append("host == \"\(h)\"")
            case .domain(let d): parts.append("host == \"\(d)\" || dnsDomainIs(host, \".\(d)\")")
            case .pattern(let p): parts.append("shExpMatch(host, \"\(p)\")")
            case .ipRange(let lo, let hi): ranges.append((lo, hi))
            }
        }
        // domain checks first, so DNS is only resolved when actually needed
        if !ranges.isEmpty {
            parts.append("__in(N(), [" + ranges.map { "[\($0.0),\($0.1)]" }.joined(separator: ",") + "])")
        }
        return parts.joined(separator: " || ")
    }

    private static func safe(_ s: String) -> String {
        s.replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: "\r", with: " ")
    }
}

// MARK: - Test / evaluation (same logic as the PAC file)

struct Evaluation {
    var host: String
    var resolvedIP: String?
    var profileName: String?
    var ruleName: String?
    var matchedTarget: String?
    var result: String
    var action: String
    /// Profiles skipped because the destination is on their exclude list
    var excludedBy: [String] = []
}

enum Evaluator {
    static func evaluate(input: String, profiles: [Profile]) -> Evaluation {
        let host = extractHost(input)
        var cached: UInt32??
        var resolved: String?
        func ip() -> UInt32? {
            if let c = cached { return c }
            var v = IPv4.parse(host)
            if v == nil, !host.contains(":"), let first = DNS.resolveIPv4(host).first {
                resolved = first
                v = IPv4.parse(first)
            }
            cached = .some(v)
            return v
        }

        var excludedBy: [String] = []
        for p in profiles {
            if let ex = p.exclusion(host: host, ip: ip) {
                excludedBy.append("\(p.name) (\(ex.description))")
                continue
            }
            for r in p.rules where r.enabled {
                if r.action == .proxy && !r.isProxyHostValid { continue }
                for t in r.parsedTargets {
                    guard let spec = t.spec else { continue }
                    let hit: Bool
                    if case .ipRange = spec { hit = spec.matches(host: host, ip: ip()) }
                    else { hit = spec.matches(host: host, ip: nil) }
                    if hit {
                        return Evaluation(host: host, resolvedIP: resolved, profileName: p.name,
                                          ruleName: r.name.isEmpty ? nil : r.name,
                                          matchedTarget: spec.description, result: r.pacResult,
                                          action: r.actionSummary, excludedBy: excludedBy)
                    }
                }
            }
        }
        return Evaluation(host: host, resolvedIP: resolved, result: "DIRECT", action: "No rule matched → DIRECT",
                          excludedBy: excludedBy)
    }

    static func extractHost(_ s: String) -> String {
        var t = s.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if t.contains("://"), let h = URL(string: t)?.host { return h }
        if let slash = t.firstIndex(of: "/") { t = String(t[..<slash]) }
        if let colon = t.lastIndex(of: ":"), t.filter({ $0 == ":" }).count == 1 { t = String(t[..<colon]) }
        return t
    }
}

// MARK: - Local PAC server (127.0.0.1 only)

final class PACServer {
    private var listener: NWListener?
    private let queue = DispatchQueue(label: "proxyrouter.pac")
    private let lock = NSLock()
    private var files: [String: String] = [:]
    var onEvent: ((String) -> Void)?

    func update(_ newFiles: [String: String]) {
        lock.lock(); files = newFiles; lock.unlock()
    }

    func start(port: Int) throws {
        stop()
        guard let nwPort = NWEndpoint.Port(rawValue: UInt16(clamping: port)) else { throw URLError(.badURL) }
        let params = NWParameters.tcp
        params.allowLocalEndpointReuse = true
        params.requiredLocalEndpoint = .hostPort(host: "127.0.0.1", port: nwPort)
        let l = try NWListener(using: params)
        l.newConnectionHandler = { [weak self] c in self?.handle(c) }
        l.stateUpdateHandler = { [weak self] st in
            if case .failed(let e) = st { self?.onEvent?("PAC server error: \(e)") }
        }
        l.start(queue: queue)
        listener = l
    }

    func stop() {
        listener?.cancel()
        listener = nil
    }

    private func handle(_ c: NWConnection) {
        c.start(queue: queue)
        receive(c, buffer: Data())
    }

    private func receive(_ c: NWConnection, buffer: Data) {
        c.receive(minimumIncompleteLength: 1, maximumLength: 16384) { [weak self] data, _, done, err in
            guard let self else { c.cancel(); return }
            var buf = buffer
            if let data { buf.append(data) }
            // drop non-HTTP connections (e.g. a TLS ClientHello) right away
            if let first = buf.first, !(65...90).contains(first) { c.cancel(); return }
            if let r = buf.range(of: Data("\r\n\r\n".utf8)) {
                self.respond(c, head: buf[..<r.lowerBound])
            } else if done || err != nil || buf.count > 65536 {
                c.cancel()
            } else {
                self.receive(c, buffer: buf)
            }
        }
    }

    private func respond(_ c: NWConnection, head: Data) {
        let text = String(decoding: head, as: UTF8.self)
        let requestLine = text.components(separatedBy: "\r\n").first ?? ""
        let parts = requestLine.split(separator: " ")
        let method = parts.first.map(String.init) ?? ""

        var status = "404 Not Found", body = "not found\n", ctype = "text/plain; charset=utf-8"
        if parts.count >= 2, method == "GET" || method == "HEAD" {
            let path = String(parts[1].split(separator: "?", maxSplits: 1).first ?? "")
            lock.lock(); let f = files[path]; lock.unlock()
            if let f {
                status = "200 OK"
                body = f
                ctype = "application/x-ns-proxy-autoconfig"
            }
        } else {
            status = "400 Bad Request"
            body = "bad request\n"
        }
        let bodyData = Data(body.utf8)
        let header = "HTTP/1.1 \(status)\r\nContent-Type: \(ctype)\r\nContent-Length: \(bodyData.count)\r\n"
            + "Cache-Control: no-cache, no-store\r\nConnection: close\r\n\r\n"
        var out = Data(header.utf8)
        if method != "HEAD" { out.append(bodyData) }
        c.send(content: out, completion: .contentProcessed { _ in c.cancel() })
    }
}
